apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: clusterpulse
    jsonData:
      database: clusterpulse
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: clusterpulse