apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterpulse-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.49.1:5433/clusterpulse
  SPRING_DATASOURCE_USERNAME: clusterpulse
  SPRING_DATASOURCE_PASSWORD: clusterpulse
  ANTHROPIC_MODEL: claude-haiku-4-5-20251001
  SPRING_FLYWAY_URL: jdbc:postgresql://192.168.49.1:5433/clusterpulse
  SPRING_FLYWAY_USER: clusterpulse
  SPRING_FLYWAY_PASSWORD: clusterpulse